remove echo

diff --git a/.github/workflows/workflow_pr.yml b/.github/workflows/workflow_pr.yml
--- a/.github/workflows/workflow_pr.yml
+++ b/.github/workflows/workflow_pr.yml
@@ -170,10 +170,11 @@ jobs:
           echo "Tag Deployed: ${{ needs.pr_deploy.outputs.terraform_container_version }}"
           echo "URL: https://${{ needs.pr_deploy.outputs.url }}"
           if
-            echo ${{ needs.ui_tests_pr_env.result }}
             ${{ needs.ui_tests_pr_env.result }} == 'success'
           then
             echo "PR environment tested, built and deployed"
             exit 0
+          else
+            echo "PR environment tested, built and deployed but UI tests failed"
+            exit 1
           fi
-          exit 1
