restore workflow

diff --git a/.github/workflows/workflow_pr.yml b/.github/workflows/workflow_pr.yml
--- a/.github/workflows/workflow_pr.yml
+++ b/.github/workflows/workflow_pr.yml
@@ -32,73 +32,70 @@ jobs:
     needs: detect_changes
     uses: ./.github/workflows/tags_job.yml
     with:
-      # changes_detected: ${{ needs.detect_changes.outputs.changes_detected }}
-      changes_detected: true
+      changes_detected: ${{ needs.detect_changes.outputs.changes_detected }}
 
-  # go_unit_tests:
-  #   name: Run Go unit tests
-  #   if: needs.detect_changes.outputs.changes_detected == 'true'
-  #   needs: create_tags
-  #   uses: ./.github/workflows/go-unit-tests.yml
-  #   with:
-  #     tag: ${{ needs.create_tags.outputs.version_tag }}
-  #     commit_sha: ${{ github.event.pull_request.head.sha }}
-  #     branch: ${{ github.head_ref }}
-  #   secrets:
-  #     pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}
-  #     codecov_token: ${{ secrets.CODECOV_TOKEN }}
+  go_unit_tests:
+    name: Run Go unit tests
+    if: needs.detect_changes.outputs.changes_detected == 'true'
+    needs: create_tags
+    uses: ./.github/workflows/go-unit-tests.yml
+    with:
+      tag: ${{ needs.create_tags.outputs.version_tag }}
+      commit_sha: ${{ github.event.pull_request.head.sha }}
+      branch: ${{ github.head_ref }}
+    secrets:
+      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}
+      codecov_token: ${{ secrets.CODECOV_TOKEN }}
 
   docker_build_scan_push:
     name: Docker Build, Scan and Push
-    if: always()
-    # if: needs.detect_changes.outputs.changes_detected == 'true' &&
-    #   (needs.go_unit_tests.result == 'success' || needs.go_unit_tests.result == 'skipped')
+    if: needs.detect_changes.outputs.changes_detected == 'true' &&
+      (needs.go_unit_tests.result == 'success' || needs.go_unit_tests.result == 'skipped')
     uses: ./.github/workflows/docker_job.yml
     needs: [
-      # go_unit_tests,
+      go_unit_tests,
       create_tags
     ]
     with:
       tag: ${{ needs.create_tags.outputs.version_tag }}
       branch_name: ${{ github.head_ref }}
 
-  # terraform_account_workflow_development:
-  #   name: TF Plan Dev Account
-  #   uses: ./.github/workflows/terraform_account_job.yml
-  #   with:
-  #     workspace_name: development
-  #   secrets:
-  #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
-  #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
-  #     pagerduty_api_key: ${{ secrets.PAGERDUTY_API_KEY }}
+  terraform_account_workflow_development:
+    name: TF Plan Dev Account
+    uses: ./.github/workflows/terraform_account_job.yml
+    with:
+      workspace_name: development
+    secrets:
+      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
+      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
+      pagerduty_api_key: ${{ secrets.PAGERDUTY_API_KEY }}
 
-  # terraform_account_workflow_preproduction:
-  #   name: TF Plan Preprod Account
-  #   needs: terraform_account_workflow_development
-  #   uses: ./.github/workflows/terraform_account_job.yml
-  #   with:
-  #     workspace_name: preproduction
-  #   secrets:
-  #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
-  #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
-  #     pagerduty_api_key: ${{ secrets.PAGERDUTY_API_KEY }}
+  terraform_account_workflow_preproduction:
+    name: TF Plan Preprod Account
+    needs: terraform_account_workflow_development
+    uses: ./.github/workflows/terraform_account_job.yml
+    with:
+      workspace_name: preproduction
+    secrets:
+      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
+      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
+      pagerduty_api_key: ${{ secrets.PAGERDUTY_API_KEY }}
 
-  # terraform_account_workflow_production:
-  #   name: TF Plan Prod Account
-  #   needs: terraform_account_workflow_development
-  #   uses: ./.github/workflows/terraform_account_job.yml
-  #   with:
-  #     workspace_name: production
-  #   secrets:
-  #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
-  #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
-  #     pagerduty_api_key: ${{ secrets.PAGERDUTY_API_KEY }}
+  terraform_account_workflow_production:
+    name: TF Plan Prod Account
+    needs: terraform_account_workflow_development
+    uses: ./.github/workflows/terraform_account_job.yml
+    with:
+      workspace_name: production
+    secrets:
+      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
+      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
+      pagerduty_api_key: ${{ secrets.PAGERDUTY_API_KEY }}
 
   ui_tests_image:
     name: Run Cypress UI Tests On Images
-    if: always()
-    # if: needs.detect_changes.outputs.changes_detected == 'true' &&
-    #   (needs.docker_build_scan_push.result == 'success' || needs.docker_build_scan_push.result == 'skipped')
+    if: needs.detect_changes.outputs.changes_detected == 'true' &&
+      (needs.docker_build_scan_push.result == 'success' || needs.docker_build_scan_push.result == 'skipped')
     uses: ./.github/workflows/ui_test_job.yml
     needs: [
       docker_build_scan_push,
@@ -116,14 +113,13 @@ jobs:
 
   pr_deploy:
       name: PR Environment Deploy
-      if: always()
-      # if: always() &&
-      #   (needs.go_unit_tests.result == 'success' || needs.go_unit_tests.result == 'skipped') &&
-      #   (needs.docker_build_scan_push.result == 'success' || needs.docker_build_scan_push.result == 'skipped') &&
-      #   (needs.ui_tests_image.result == 'success' || needs.ui_tests_image.result == 'skipped')
+      if: always() &&
+        (needs.go_unit_tests.result == 'success' || needs.go_unit_tests.result == 'skipped') &&
+        (needs.docker_build_scan_push.result == 'success' || needs.docker_build_scan_push.result == 'skipped') &&
+        (needs.ui_tests_image.result == 'success' || needs.ui_tests_image.result == 'skipped')
       needs: [
         create_tags,
-        # go_unit_tests,
+        go_unit_tests,
         docker_build_scan_push,
         ui_tests_image
       ]
@@ -173,26 +169,26 @@ jobs:
       aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
       aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
 
-  # end_of_pr_workflow:
-  #   name: End of PR Workflow
-  #   runs-on: ubuntu-latest
-  #   if: always()
-  #   environment:
-  #     name: "dev_${{ needs.create_tags.outputs.environment_workspace_name }}"
-  #     url: "https://${{ needs.pr_deploy.outputs.url }}"
-  #   needs: [pr_deploy, create_tags, ui_tests_pr_env]
-  #   steps:
-  #     - name: End of PR Workflow
-  #       run: |
-  #         echo "${{ needs.pr_deploy.outputs.terraform_workspace_name }} PR environment tested, built and deployed"
-  #         echo "Tag Deployed: ${{ needs.pr_deploy.outputs.terraform_container_version }}"
-  #         echo "URL: https://${{ needs.pr_deploy.outputs.url }}"
+  end_of_pr_workflow:
+    name: End of PR Workflow
+    runs-on: ubuntu-latest
+    if: always()
+    environment:
+      name: "dev_${{ needs.create_tags.outputs.environment_workspace_name }}"
+      url: "https://${{ needs.pr_deploy.outputs.url }}"
+    needs: [pr_deploy, create_tags, ui_tests_pr_env]
+    steps:
+      - name: End of PR Workflow
+        run: |
+          echo "${{ needs.pr_deploy.outputs.terraform_workspace_name }} PR environment tested, built and deployed"
+          echo "Tag Deployed: ${{ needs.pr_deploy.outputs.terraform_container_version }}"
+          echo "URL: https://${{ needs.pr_deploy.outputs.url }}"
 
-  #         if ${{ contains(needs.ui_tests_pr_env.result,'success') }}
-  #         then
-  #           echo "PR environment tested, built and deployed"
-  #           exit 0
-  #         else
-  #           echo "PR environment tested, built and deployed but UI tests failed"
-  #           exit 1
-  #         fi
+          if ${{ contains(needs.ui_tests_pr_env.result,'success') }}
+          then
+            echo "PR environment tested, built and deployed"
+            exit 0
+          else
+            echo "PR environment tested, built and deployed but UI tests failed"
+            exit 1
+          fi
